site_name: KDY International Sailing School Docs
repo_url: https://github.com/x123/kdy-iss
theme:
  name: material
validation:
  omitted_files: warn
  absolute_links: warn  # Or 'relative_to_docs' - new in MkDocs 1.6
  unrecognized_links: warn
  anchors: warn  # New in MkDocs 1.6
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - toc:
      permalink: "#"
      baselevel: 2
nav:
  - KDY International Sailing School: index.md
  - DS37 Manual: ds37.md
