site_name: KDY International Sailing School
repo_url: https://github.com/x123/kdy-iss
theme:
  name: material
  features:
    - navigation.footer
    - navigation.expand
    - navigation.sections
    - navigation.tracking
    - navigation.top
    - toc.follow
    - toc.integrate
  logo: img/kdy-logo.png
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode

    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/weather-night
        name: Switch to light mode
extra:
  generator: false
validation:
  omitted_files: warn
  absolute_links: warn  # Or 'relative_to_docs' - new in MkDocs 1.6
  unrecognized_links: warn
  anchors: warn  # New in MkDocs 1.6
markdown_extensions:
  - admonition
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.details
  - pymdownx.superfences
  - toc:
      permalink: "#"
      baselevel: 2
nav:
  - 'Getting Started': index.md
  - 'KDY ISS':
    - 'Information for Skippers': skippers.md
    - 'Safety':
      - 'In Case of Injury': in-case-of-injury.md
      - 'General Safety Information': kdy-safety.md
    - 'Pre-Departure Checklist': pre-departure-checklist.md
    - 'After-Sailing Checklist': after-sailing-checklist.md
    - 'Skovshoved':
      - 'Harbour Information': skovshoved.md
      - 'Harbour Manoeuvres': skovshoved-manoeuvres.md
  - 'DS37 Manual':
    - 'Introduction': intro.md
    - 'The DS37': the-ds37.md
    - 'DS37-specific Safety': ds37-safety.md
    - 'Sail Handling': sail-handling.md
    - 'Manoeuvres': manoeuvres.md
