site_name: KDY International Sailing School
repo_url: https://github.com/x123/kdy-iss
theme:
  name: material
  features:
    - navigation.footer
extra:
  generator: false
validation:
  omitted_files: warn
  absolute_links: warn  # Or 'relative_to_docs' - new in MkDocs 1.6
  unrecognized_links: warn
  anchors: warn  # New in MkDocs 1.6
markdown_extensions:
  - admonition
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.details
  - pymdownx.superfences
  - toc:
      permalink: "#"
      baselevel: 2
nav:
  - 'Getting Started': index.md
  - 'KDY ISS':
    - 'Information for Skippers': skippers.md
    - 'Pre-Departure Checklist': pre-departure-checklist.md
    - 'After-Sailing Checklist': after-sailing-checklist.md
    - 'Skovshoved': skovshoved.md
  - 'DS37 Manual':
    - 'Introduction': intro.md
    - 'The DS37': the-ds37.md
    - 'Safety': safety.md
    - 'Sail Handling': sail-handling.md
    - 'Manoeuvres': manoeuvres.md
